general {
    lock_cmd = /home/amanhex/.config/quickshell/pill/scripts/lock.sh
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 60
    on-timeout = /home/amanhex/.config/quickshell/pill/scripts/lock.sh
}

listener {
    timeout = 180
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
